# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bubble.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bubble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ubble.proto\x12\x06\x62ubble\"\x1e\n\x0bSortRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"\x1c\n\tSortReply\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x32@\n\x06Sorter\x12\x36\n\nBubbleSort\x12\x13.bubble.SortRequest\x1a\x11.bubble.SortReply\"\x00\x42\x1b\n\x17io.grpc.examples.bubbleP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bubble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027io.grpc.examples.bubbleP\001'
  _globals['_SORTREQUEST']._serialized_start=24
  _globals['_SORTREQUEST']._serialized_end=54
  _globals['_SORTREPLY']._serialized_start=56
  _globals['_SORTREPLY']._serialized_end=84
  _globals['_SORTER']._serialized_start=86
  _globals['_SORTER']._serialized_end=150
# @@protoc_insertion_point(module_scope)
